### ISSUE TITLE
Unordered list is not rendering properly

### ISSUE THREAD

**Issue by hossainemruz** [hossainemruz/toha#126]
## Expected Behavior
Unordered list should have bullet before it.

## Current Behavior

There is not bullet before unordered list.

## Possible Solution
Fix the following CSS. It should only select the `ul` elements of sidebar.
```css
.tree, ul {
    margin: 0;
    padding: 0;
    list-style: none;
}
```

## Steps to Reproduce

1.
2.
3.
4.

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11
