### ISSUE TITLE
Changing of Deafult Logo at the Header

### ISSUE THREAD

**Issue by HabibRh26** [hossainemruz/toha#65]
Is it Possible to Change the "toha" deafult image logo at the top left of header? How can I do this?

**Comment by llaniewski** [comment]
In the `config.yaml` file, you have options to set the logo:
```yaml
  logo:
    main: /assets/images/main-logo.png
    inverted: /assets/images/inverted-logo.png
```
